### PR TITLE
Testing Your Ruby Code - Enumerable

### PR DESCRIPTION
**Pull request by arthurborgesdev**
Tests have been added with the test framework RSpec.

They were added to the enumerable_methods_spec.rb file and tested against the enumerable_methods.rb file.

The following methods were created/tested:

Enumerable module:

- #my_each
- #my_each_with_index
- #my_select
- #my_all?
- #my_any?
- #my_none?
- #my_count
- #my_map
- #my_inject

Outside of Enumerable module:

- #multiply_els

A total of 43 test cases were written.

### CODE REVIEW

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️✍️

You have a great project so far, I really love the effort you gave in testing your code.

## To Highlight
- Clear commit messages
- Really great PR description
- Great testing all your enumerable methods 👏
- Good use of git-flow
- You have really a great test coverage💯

## To Improve
- [x] Your rubocop is failing, you can run `rubocop` to check these errors, you can also run `rubocop -A` to fix the auto-correctable ones, note that not all of them may be auto-correctable. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/section/clean_code_requirement.png) from Pathwright)


Please fix this issue and resubmit for review. Happy coding 🤓💻.

> #### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

**Comment by cyonii** [comment]
The screenshot below shows the result of running `rubocop` on your project.
<br>

Screenshot 2021-04-06 at 12 59 28 AM

**Review by mke2111 — APPROVED** [review]
# STATUS: APPROVED  🟡

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval.

### You may now merge to the main branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

**Comment by arthurborgesdev** [comment]
@cyonii That's because I hadn't commit my .rubocop.yml.

You can see that everything runs fine on my computer:

image

Just download the repo again and see.

Thank you!

**Pull request merged**
